### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by iScrE4m** [aio-libs/idna-ssl#5]
Hey, my piplines for 3.7.-dev are failing because idna-ssl requires <3.7.0. Could this be checked for compatibility and bumped in requirements? :)

**Comment by asvetlov** [comment]
You should not install the library on Python 3.7
New Python has fixes in ssl module, it means the library is not needed anymore.

**Comment by iScrE4m** [comment]
Ah, that's interesting. I thought it must be aiohttp not detecting python, but they are. Turns out `Pipfile.lock` being made in Python 3.6 includes idna_ssl and that breaks my 3.7. build. Thanks!
