### ISSUE TITLE
Open support for Python 3.7

### ISSUE THREAD

**Issue by wschwab** [aio-libs/idna-ssl#6]
`setup.py` still requires `python_requires='<3.7.0'` (line 38), while the README seems to indicate that it's ready for 3.7.

**Comment by asvetlov** [comment]
The library is a workaround for Python<3.7 bug.
It should not be installed on Python 3.7 and doesn't work with this version.
README doesn't say that the library is available on 3.7.

**Comment by wschwab** [comment]
Okay, I misunderstood. If I'm running 3.7, and building a library that lists idna-ssl as a requirement, what should I do?

**Comment by asvetlov** [comment]
Perhaps you should not list `idna-ssl` in your requirements at all.
Or use conditional environment marker like `idna-ssl==1.0.1; python_version<"3.7"`
