### ISSUE TITLE
Fix 3.7.2 support

### ISSUE THREAD

**Issue by guiscaranse** [aio-libs/idna-ssl#64]
Since Python 3.7 is supported it should support 3.7.* and not only 3.7.0.

**Comment by webknjaz** [comment]
Does anything specific not work for you?

**Comment by guiscaranse** [comment]
It is not possible to install idna-ssl using Python 3.7.2

**Comment by webknjaz** [comment]
I can't see any place in metadata with such limitation. Maybe it was removed in master and only exists on PyPI or maybe it's just yet another bug of Pipenv. Have you tried checking it with normal Pip?

Anyway, leaving this to @hellysmile as it's his package mostly.

**Comment by guiscaranse** [comment]
It may be a PyPi only issue, I replaced the source package with the Github one and It worked. But, PyPi works with pip on 3.7.2, can't confirm for sure if it is a problem with Pipenv itself but it should not, since it is possible to make this work using the repo source.

**Comment by webknjaz** [comment]
Look at https://pypi.org/project/idna_ssl/1.0.1/, it has `Requires: Python <3.7.0` in the left sidebar. But the newer one doesn't: https://pypi.org/project/idna_ssl/1.1.0/.
So just use v1.1.0.
